Create code flows with opensource.md
flossway/flossway pull request #31
Opened 2022-02-24 06:50 UTC by kailakx

Tison, would you please to take a review?@tison

2022-02-24 07:13 UTC, tisonkun requested changes
Thanks for submitting this PR. Please add metadata info and address format comments inline.

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +
Please add metadata as other posts do.

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +
```suggestion

<!-- more -->

```

You may add a summary mark. See also other posts also.

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +这是Linus 于 2000 年 8 月 25 日在社区邮件列表上讨论关于 Linux 内核线程优化问题时，其中一个人提出了个他认为非常高效的方案，而 Linus 认为这个方案不够好，于是他在回信中就写下了这句在今天足以堪称经典的话，这也令很多程序员感觉非常惬意。
```suggestion
这是 Linus 于 2000 年 8 月 25 日在社区邮件列表上讨论关于 Linux 内核线程优化问题时，其中一个人提出了个他认为非常高效的方案，而 Linus 认为这个方案不够好，于是他在回信中就写下了这句在今天足以堪称经典的话，这也令很多程序员感觉非常惬意。
```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +
```suggestion
```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +
```suggestion
```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +# 代码胜于雄辩
```suggestion
## 代码胜于雄辩
```

Heading 1 is for title and reserved for content.

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +# 知识的显性化和去粘性
```suggestion
## 知识的显性化和去粘性
```

Heading 1 is for title and reserved for content.

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +2）知识的去粘性
```suggestion

1. 知识的显性化
2. 知识的去粘性
```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +读上几遍还是只能感慨文字的美，每一个词都有丰富的含义和实质，既有深刻的暗示性，犹如乙醚般清淡，想要捕捉时它却从指尖溜走。 从这段评论中，我们可以看出在日常语言下，即使对于一个专业的作家而言，知识显性化的提取也是非常高难度。当然，菲茨•吉拉德用显性语言来故意蕴藏他想表达的隐含之美是另外一层艺术创作境界，而对于可以我们得出的一个结论是：日常语言对于知识的显性化传递是无法做到足够清晰的，同时，那些受高
```suggestion

> 读上几遍还是只能感慨文字的美，每一个词都有丰富的含义和实质，既有深刻的暗示性，犹如乙醚般清淡，想要捕捉时它却从指尖溜走。 从这段评论中，我们可以看出在日常语言下，即使对于一个专业的作家而言，知识显性化的提取也是非常高难度。当然，菲茨•吉拉德用显性语言来故意蕴藏他想表达的隐含之美是另外一层艺术创作境界，而对于可以我们得出的一个结论是：日常语言对于知识的显性化传递是无法做到足够清晰的，同时，那些受高度语境限制且不确定的语言则更会成为粘性知识。所谓粘性知识是指必须通过近距离的观察和沟通甚至面对面的jiaotan通才能了解获得的知识。
```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> + 大家应该知道，有个一个古老的游戏叫“拷贝不走样”。百度百科中是这样描述的：规则是先给第一个人看他要表演的话语或素材，第二个表演给第三个看，依次下传。最后一人要把他理解的意思讲出来，猜中则胜利。该游戏起源于曾经在上海电视台热播的综艺节目《智力大冲浪》。节目最早的版本其实是，人们隔着厚厚的移动墙向下一个选手传与该词相关的动作，然后最后一个人说出第一个人做的姿势的含义，往往笑倒一片观众，拷贝不走样的
```suggestion
 大家应该知道，有个一个古老的游戏叫“拷贝不走样”。百度百科中是这样描述的：规则是先给第一个人看他要表演的话语或素材，第二个表演给第三个看，依次下传。最后一人要把他理解的意思讲出来，猜中则胜利。该游戏起源于曾经在上海电视台热播的综艺节目《智力大冲浪》。节目最早的版本其实是，人们隔着厚厚的移动墙向下一个选手传与该词相关的动作，然后最后一个人说出第一个人做的姿势的含义，往往笑倒一片观众，拷贝不走样的游戏性在于“拷贝走样”。在活动中，观众可以亲眼目睹动作渐渐走样，这是因为，清楚知道词语的 B 不一定能表达相同信息给后面的 C，动作的模仿中关键的“细节”容易遗漏，或是被 C、D、E 等人再创造而传承。
```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +编译成二进制且不提供源代码的程序，虽然通过运行可以看到显性结果或者使用，但事实上因为代码的不可见就是一种典型的隐性且粘性的知识。传统的软件提供商在提供可运行的软件时会附带软件使用手册或者技术文档来局部显性化，也会通过一些面对面的交流沟通（这些往往以培训，现场指导等形式出现）来局部去粘性。但最直接和最透彻的显性化无疑就是提供源代码。当初自由软件运动和随后兴起的开源运动的初心，就是为了让代码知识显性
```suggestion

实际上，这个游戏的隐含意义就是粘性知识在信息的传递过程中，由于传递者自身及语言，动作姿势的模糊性及多义性，信息会被迅速衰减。从这个游戏的结果，我们大致可以得出一个粗浅的结论：粘性知识的传播是距离的衰减函数。

编译成二进制且不提供源代码的程序，虽然通过运行可以看到显性结果或者使用，但事实上因为代码的不可见就是一种典型的隐性且粘性的知识。传统的软件提供商在提供可运行的软件时会附带软件使用手册或者技术文档来局部显性化，也会通过一些面对面的交流沟通（这些往往以培训，现场指导等形式出现）来局部去粘性。但最直接和最透彻的显性化无疑就是提供源代码。当初自由软件运动和随后兴起的开源运动的初心，就是为了让代码知识显性化的无损穿流。
```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +
```suggestion
  
```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +# 我们的结论
```suggestion
## 我们的结论 
```

Heading 1 is for title and reserved for content.

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +软件代码的开源是软件知识显性化的最优方式，而积极的开源社区活动则是软件知识去粘性化的最佳手段。
```suggestion
### 结论 1：开源的软件代码是软件类知识传递损耗系数最小的传递载体

软件代码的开源是软件知识显性化的最优方式，而积极的开源社区活动则是软件知识去粘性化的最佳手段。
```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +前不久，Apache基金会主席David Nelly在美国参议院的听证会上所言中看到，开源已经成为数字经济的重要基础设施。那么程序代码必然是开源创新协同的重要载体。Linux基金会的执行董事Jim Zemlin曾经在2013年的一次TEDx演讲中提到这样一些数据：荷马史诗《伊利亚德》15,000行，《战争与和平》45万字，在Linux项目中，每一天的每一小时至少有7个变化在 Linux项目里发生
```suggestion
前不久，Apache 基金会主席 David Nelly 在美国参议院的听证会上所言中看到，开源已经成为数字经济的重要基础设施。那么程序代码必然是开源创新协同的重要载体。Linux 基金会的执行董事 Jim Zemlin 曾经在 2013 年的一次 TEDx 演讲中提到这样一些数据：荷马史诗《伊利亚德》15,000 行，《战争与和平》45 万字，在 Linux 项目中，每一天的每一小时至少有 7 个变化在 Linux 项目里发生，仅 2012 年就有近一百万行的代码被提交，这又是由分布在全球的 407 个公司、几千个程序员一起合作产生的结果。到今天，Linux 毫无疑义地已经成为在过去 30 年以来最成功的全球化开源协作项目。正是这些 Linux 里开源的代码穿越了时间，跨越了地理空间，更涵盖了不同种族的人群，进而造就了人类软件史上的一次伟大奇迹，这几乎和代码穿流的力量密不可分。由此，我们可以得到了代码穿流的另一个结论：
```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +## 结论2.开源的代码在时间，空间和不同人群之间穿流的程度决定了这个开源社区的价值。
```suggestion

### 结论 2：开源的代码在时间，空间和不同人群之间穿流的程度决定了这个开源社区的价值
```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +
```suggestion

```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +代码穿流后，软件代码知识就不再是时间和空间的衰减函数，反而可能成为时间和空间的递增函数。进一步而言，开源社区也未必会因为多样化成岩和多元化角色间的差异衰减社区价值，它们可能表现为随着社区成员多样化和多元化，并随着成员间的争论增多而更显得有价值。那时，如果开源社区的代码如果想更快更新迭代，也未必需要社区成员很擅长懂得如何协作，也未必需要每个社区成员成为一个不敢争论的“老好人”，社区可能更多需要的是
```suggestion
代码穿流后，软件代码知识就不再是时间和空间的衰减函数，反而可能成为时间和空间的递增函数。进一步而言，开源社区也未必会因为多样化成岩和多元化角色间的差异衰减社区价值，它们可能表现为随着社区成员多样化和多元化，并随着成员间的争论增多而更显得有价值。那时，如果开源社区的代码如果想更快更新迭代，也未必需要社区成员很擅长懂得如何协作，也未必需要每个社区成员成为一个不敢争论的“老好人”，社区可能更多需要的是能够经常进行相互批评并能捍卫自己的想法的成员，当然这里有一个必要的前提就是对于所有的争论，最后能够以 show me the code 来终结，而 show me the code 也足以让争论分出胜负。也许我的这个想法有些乌托邦，但事实可能也就如此。
```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +而关于激烈辩论有利于创新这一点，在2003年伯克利大学曾经做过一次称作"一个想法是如何被创造出来的？的实验。当时，一些实验者被分成两组，其中一个组采用“传统的头脑风暴法”，即该组成员不相互批评、而鼓励每个被提出来的想法，认为没有一个想法是坏的想法。另外一个组则采用"激烈辩论法"，即小组成员相互批评各自想法，鼓励以积极的辩论去捍卫自己的想法。出乎我们的意料，这个实验最后的结果竟然是激烈辩论法的那一
```suggestion
而关于激烈辩论有利于创新这一点，在 2003 年伯克利大学曾经做过一次称作“一个想法是如何被创造出来的？”的实验。当时，一些实验者被分成两组，其中一个组采用“传统的头脑风暴法”，即该组成员不相互批评、而鼓励每个被提出来的想法，认为没有一个想法是坏的想法。另外一个组则采用“激烈辩论法”，即小组成员相互批评各自想法，鼓励以积极的辩论去捍卫自己的想法。出乎我们的意料，这个实验最后的结果竟然是激烈辩论法的那一组获胜，相比头脑风暴组而言，他们反而产生了高出头脑风暴组一个数量级的好想法。由此，我们又得出第三个结论：
```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +## 结论 3.  开源社区内的激烈争论将有利于开源软件的创新。
```suggestion
### 结论 3：开源社区内的激烈争论将有利于开源软件的创新
```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +Jim Zemlin在那年的TEDx演讲中还如此动情地讲到：>All of us are smarter than any one of us.  there is a whole generation of code poets out there, working furiously. Poets who love what they do, they may not get along,
```suggestion

当然，这基于代码语言的精准表达性和代码编译运行后的可校验性的前提。

Jim Zemlin 在那年的 TEDx 演讲中还如此动情地讲到：

> All of us are smarter than any one of us.  there is a whole generation of code poets out there, working furiously. Poets who love what they do, they may not get along, but are creating ... These individuals have created the coal and steel of the information age ... The future is a world in which can enrich your self, while at the same time enriching others.
```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +也恰如关于乔布斯生前往事的纪录片《失落的访谈》中曾记录了乔布斯在1995年接受的采访中所提到的一个观点，程序语言在未来应当像其他我们日常所用来沟通的语言一样，成为我们每个人必备的交流工具。虽然这对一般普通人要求过高，但无疑他看到了代码语言作为思想的传达载体具有比数学更具象，比语言更精准的表达。
```suggestion
也恰如关于乔布斯生前往事的纪录片《失落的访谈》中曾记录了乔布斯在 1995 年接受的采访中所提到的一个观点，程序语言在未来应当像其他我们日常所用来沟通的语言一样，成为我们每个人必备的交流工具。虽然这对一般普通人要求过高，但无疑他看到了代码语言作为思想的传达载体具有比数学更具象，比语言更精准的表达。
```

2022-02-24 07:13 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +如今开源的代码已经成为了软件知识传递过程中的一种最佳工具和载体。开源的内在价值取决于开源的代码在时间，空间和不同人群间的无损穿流力。我们也由此相信，任何一个开源项目的创建者在明白了开源的生命力和创新力来源于代码的穿流力之后，他们应该可以在他们所处的环境里去做出一个理智的选择，除非他们已经放弃了开源的初衷。
```suggestion
## 抉择

如今开源的代码已经成为了软件知识传递过程中的一种最佳工具和载体。开源的内在价值取决于开源的代码在时间，空间和不同人群间的无损穿流力。我们也由此相信，任何一个开源项目的创建者在明白了开源的生命力和创新力来源于代码的穿流力之后，他们应该可以在他们所处的环境里去做出一个理智的选择，除非他们已经放弃了开源的初衷。
```

2022-02-25 13:33 UTC, kailakx commented on source/_posts/code flows with opensource.md
> +
---
title: 大教堂过时了吗
date: 2022-02-18
author: 狄安
categories: 狄安
tags:
    - 开源
    - 开源协同
---

2022-02-25 13:44 UTC, kailakx reviewed
tison, would you please check it is ok or not?

2022-02-25 13:44 UTC, kailakx commented on source/_posts/code flows with opensource.md
> +
---
title:  代码穿流-迷失的开源乌托邦之三
date: 2022-02-25
author: 狄安
categories: 狄安
tags:
    - 开源
    - 开源协同
---

2022-02-25 13:44 UTC, kailakx commented on source/_posts/code flows with opensource.md
> +
<!-- more -->

2022-02-25 13:45 UTC, kailakx reviewed
tison, would you please check it is ok or not?

2022-02-25 13:45 UTC, kailakx reviewed
tison, would you please check it is ok or not?

2022-02-25 13:45 UTC, kailakx reviewed
tison, would you please check it is ok or not?

2022-02-25 13:45 UTC, kailakx reviewed
tison, would you please check it is ok or not?

2022-02-25 13:45 UTC, kailakx reviewed
tison, would you please check it is ok or not?

2022-02-25 13:45 UTC, kailakx reviewed
tison, would you please check it is ok or not?

2022-02-25 16:21 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +
```suggestion
---
title:  代码穿流-迷失的开源乌托邦之三
date: 2022-02-25
author: 狄安
categories: 狄安
tags:
    - 开源
    - 开源协同
---
```

2022-02-25 16:22 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +Facebook 创始人扎克伯格也曾在自己公司上市的前一天发表的上市演讲中说过了类似的话，他当是这样说的：“Code wins argument”，即“代码胜于雄辩。” 其言下之意是想说两层意思：1.代码是一种比平常语言更能精确表达思想的工具。2.代码运行出来的结果可以见证想法的恰当与否。
```suggestion
Facebook 创始人扎克伯格也曾在自己公司上市的前一天发表的上市演讲中说过了类似的话，他当是这样说的：“Code wins argument”，即“代码胜于雄辩。” 其言下之意是想说两层意思：

1. 代码是一种比平常语言更能精确表达思想的工具。
2. 代码运行出来的结果可以见证想法的恰当与否。
```

2022-02-25 16:22 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +
```suggestion
  
```

2022-02-25 16:23 UTC, tisonkun commented on source/_posts/code flows with opensource.md
> +所以开源软件实践中，程序员通过代码编写将自己的想法精确表达出来，并且通过代码开源行动开放共享出来，就是一次非常典型的知识显性化过程，随后通过社区开展的各类活动如论坛,meetup,会议等线上线下活动进行知识的去粘性化，进而让显性化的代码知识在开源社区的不同成员间无损穿流达到分享传递和协同，让不同程序员的匠性得以聚合，最终达到社会化协同创新。
```suggestion
所以开源软件实践中，程序员通过代码编写将自己的想法精确表达出来，并且通过代码开源行动开放共享出来，就是一次非常典型的知识显性化过程，随后通过社区开展的各类活动如论坛，meetup，会议等线上线下活动进行知识的去粘性化，进而让显性化的代码知识在开源社区的不同成员间无损穿流达到分享传递和协同，让不同程序员的匠性得以聚合，最终达到社会化协同创新。
```

2022-02-25 16:35 UTC, merged

2022-02-25 16:35 UTC, tisonkun commented
@kailakx Thanks for sending this PR! I made some polishes and rename the file. Now merged.