Create opensource-code-spillover.md
flossway/flossway pull request #40
Opened 2022-03-07 10:48 UTC by kailakx

hi tison, here is my new PR. Would you please check it ? @tisonkun

2022-03-07 11:28 UTC, tisonkun commented
@kailakx Thanks for submitting this PR! I'll review it tomorrow.

2022-03-08 08:17 UTC, tisonkun requested changes
Thanks for your submission! Comments inline.

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +它的拥有者是微软公司，不是开源组织。所以，即使哪一天 Github真宣布对俄罗斯程序员禁用，大家需要清楚的一点是，那不是开源对俄罗斯程序员的禁用，而是微软公司的决定而已。
```suggestion
这几天由于俄乌战争影响，网络上有消息传 GitHub 要制裁俄罗斯，以至于有人惊呼开源也政治化了。在这里就不得不和大家普及一下 Github 不代表开源，Github 只是代表着托管开源软件的一个商业平台，它的拥有者是微软公司，不是开源组织。所以，即使哪一天  Github 真宣布对俄罗斯程序员禁用，大家需要清楚的一点是，那不是开源对俄罗斯程序员的禁用，而是微软公司的决定而已。
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +它的拥有者是微软公司，不是开源组织。所以，即使哪一天 Github真宣布对俄罗斯程序员禁用，大家需要清楚的一点是，那不是开源对俄罗斯程序员的禁用，而是微软公司的决定而已。
Please take care of format by yourself. It's too much for a reviewer to spot all of these case for one contributor many times.

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +## 1.开源溢出的是一种公共知识
```suggestion
## 开源溢出的是一种公共知识
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +或者基金会组织采取一些极端的行动。
```suggestion
开源软件作为一种从开源社区溢出的代码知识，其属性随着开源的那一刻，就在与它一起发布的开源许可协议内都定义清楚了。事实上，开源软件作为公共知识的一种，是很难去禁止谁的。除非，开源软件所属的开源社区或者基金会组织采取一些极端的行动。
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +技术和知识罢了。
```suggestion
在 SAP、Apple、Google 等科技巨头公司宣布停止对俄罗斯的服务后，网络媒体上甚至冒出了“技术还有国界吗？”的言论。当然，这也可以理解，作为一个科技公司，肯定是有国界的，也完全可以选择自己的政治立场。

但，科技公司并不就简单等价于科技知识。至于技术和知识有没有国界，其实这是要区分清楚的。因为知识分为公共知识和私有知识。“科学没有国界，科学家是有祖国的。” 这句话里对于科学没有国界的表达，指的就应该是人类所共有的那些公共的科学知识，而科学家在公共知识下通过自身所掌握的的一些专有和私有化知识确实会产生国界的。所以，如今，如果说那些宣称暂停服务所代表的技术，充其量就是一些科技公司所拥有的私有技术和知识罢了。
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +然后形成知识溢出，于是成为了一种人类的公共知识。因为开源的知识表现为代码形式，所以我也把这种现象称作开源代码溢出。
```suggestion
而作为人类所共同拥有的公共知识，不仅是科学家或技术专家们用于形成私有知识的基础，更是推动社会经济增长的驱动力。我们今天要聊的开源话题，就是软件因为代码的开源开放后，在开源社区产生了知识的显性化，然后形成知识溢出，于是成为了一种人类的公共知识。因为开源的知识表现为代码形式，所以我也把这种现象称作开源代码溢出。
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +## 2.开源代码溢出
```suggestion
## 开源代码溢出
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +进一步而言，知识溢出是什么？这是经济学家保罗•罗默（Paul M. Romer），新增长理论的创建者，首先系统性提出了知识溢出的观点。他把知识完整纳入到经济和技术体系之内，建立了两个著名的内生经济增长模型，然后用来解释经济的增长，并得出了一个重要的观点：知识溢出所形成的公共知识是推动技术进步的一个重要基础，而技术进步是推动经济增长的驱动力。他也因为这些理论成就和威廉•诺德豪斯(William D
```suggestion
进一步而言，知识溢出是什么？这是经济学家保罗•罗默（Paul M. Romer），新增长理论的创建者，首先系统性提出了知识溢出的观点。他把知识完整纳入到经济和技术体系之内，建立了两个著名的内生经济增长模型，然后用来解释经济的增长，并得出了一个重要的观点：知识溢出所形成的公共知识是推动技术进步的一个重要基础，而技术进步是推动经济增长的驱动力。他也因为这些理论成就和威廉•诺德豪斯(William D. Nordhaus)共同获得了 2018 年度的诺贝尔经济学奖。
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +## 3.诺奖模型下代码溢出之经济学函数表达
```suggestion
## 诺奖模型下代码溢出之经济学函数表达
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +罗墨的新增长理论有两个模型，一个是假设在完全竞争条件下基于知识溢出的内生增长模型，另一个是假设在非完全竞争和部分知识垄断下的内生增长模型。有兴趣的朋友可以把他的论文找出来仔细学习一下。在开源生态中，如果严格按照OSI(Open Source Initiative)即开放源代码促进会制定的开源标准来发布的开源软件，实际上就属于罗墨假设在完全竞争条件下的第一个知识溢出模型。那么，按照罗默给出的第一个
```suggestion
罗墨的新增长理论有两个模型，一个是假设在完全竞争条件下基于知识溢出的内生增长模型，另一个是假设在非完全竞争和部分知识垄断下的内生增长模型。有兴趣的朋友可以把他的论文找出来仔细学习一下。在开源生态中，如果严格按照开放源代码促进会（OSI, Open Source Initiative）制定的开源标准来发布的开源软件，实际上就属于罗墨假设在完全竞争条件下的第一个知识溢出模型。那么，按照罗默给出的第一个数学模型，就让我们试着从开源使用方角度来阐述一下代码溢出后的经济学分析，我们就可以给出一个开源使用方的生产函数表达式：
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +V=∑_(i=1)^n▒Vi                (2)
Malformed formula, please rewrite with valid syntax.

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +    Xi： 为厂商的投入要素向量(如资金，设备等)；
```suggestion
* Y 为使用了开源技术的使用方的产出水平；
* Ki 为企业为产品拥有的专有知识；
* V 则为企业可以拥有的开源软件的知识总量水平；
* Xi 为厂商的投入要素向量(如资金，设备等)；
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +对于表达式（2），则可以这样理解：开源代码溢出的公共知识水平总量（V)由所有的开源社区贡献方的代码贡献水平(Vi)的总和来决定。
```suggestion
对于表达式（2），则可以这样理解：开源代码溢出的公共知识水平总量（V) 由所有的开源社区贡献方的代码贡献水平 (Vi) 的总和来决定。
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +
```suggestion
## 开源代码溢出生产函数下的经济学分析

```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +2）在所拥有的开源代码溢出总水平量下，其所能实现的的转化率大小。
```suggestion
1. 其所在生态内可以触达的开源代码溢出水平的总量大小;
2. 在所拥有的开源代码溢出总水平量下，其所能实现的的转化率大小。
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +
```suggestion
进而，我们也可以看到在去年年底因为一个被广泛使用的开源软件 Log4j。因为严重的安全漏洞而引发的各类对于开源软件使用担忧的言论以及开源软件的责任方问题，其实这样的困境我们也就迎刃而解，按照这个表达式来看，实际这就是对于一个有效 V 值的求解而已。

```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +
```suggestion
1. 不以OSI开源许可的标准来发布代码，并开发更多自身专属的私有技术知识来提升Ki值;
2. 通过增加开源许可协议的条款限制来设法降低公有云厂商对开源代码溢出总量的使用和转化。
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +开源代码溢出的总量水平V，对于任何一个使用方而言，其实在开源知识溢出的那一刻，已经是个给定的值。
```suggestion
开源代码溢出的总量水平 V，对于任何一个使用方而言，其实在开源知识溢出的那一刻，已经是个给定的值。
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +按照上述第二个表达式，V 就是所有开源贡献者的代码贡献总水平。开源社的庄表伟老师前段时间发表了一篇试论 <开源生态的经济模型>，文章从传统的劳动价值理论，初步假设了一个以劳动时间为变量的开源生态经济学模型，并建议以贡献者在开源社区投入的必要劳动时间来定义开源软件的经济学价值，以开源社区的总劳动时间来定义开源社区的活跃度。这的确给出了一个来分析开源生态经济学价值很好的思路。
```suggestion
按照上述第二个表达式，V 就是所有开源贡献者的代码贡献总水平。开源社的庄表伟老师前段时间发表了一篇[《试论开源生态的经济模型》](economic-model-of-open-source-ecology.md)，文章从传统的劳动价值理论，初步假设了一个以劳动时间为变量的开源生态经济学模型，并建议以贡献者在开源社区投入的必要劳动时间来定义开源软件的经济学价值，以开源社区的总劳动时间来定义开源社区的活跃度。这的确给出了一个来分析开源生态经济学价值很好的思路。
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +V=∑_(i=1)^n▒Vi=∑_(i=1)^n▒V(K_I,V,Xi) +V
Malformed formula, please rewrite with valid syntax.

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +
```suggestion
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +## 4.代码溢出模型下的开源建议
```suggestion
## 代码溢出模型下的开源建议
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +人力资本理论的提出者是威廉•诺德豪斯(William D. Nordhaus)，他在2018年和罗墨一同获得了诺奖。以他们的观点对应到开源现象，我们则可以这样来解读，虽然贡献方因为既有开源的代码贡献形成了公共知识后不再对这部分知识具有垄断性和排他性，但贡献方本身作为人力资本的拥有方却是具有天生的排他性和垄断性的，而这些有价值的人力资本的新思想却是不断涌现的，从而将有效保持贡献方的竞争力。所以，贡
```suggestion
人力资本理论的提出者是威廉•诺德豪斯(William D. Nordhaus)，他在 2018 年和罗墨一同获得了诺奖。以他们的观点对应到开源现象，我们则可以这样来解读，虽然贡献方因为既有开源的代码贡献形成了公共知识后不再对这部分知识具有垄断性和排他性，但贡献方本身作为人力资本的拥有方却是具有天生的排他性和垄断性的，而这些有价值的人力资本的新思想却是不断涌现的，从而将有效保持贡献方的竞争力。所以，贡献方可能会因为自己的开源贡献而失去局部或者阶段性的竞争力，但他们所拥有的人力资本的排他性和垄断性最终将决定它的竞争力，除非它失去了这部分人力资本。
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +## 5.开源的远眺
```suggestion

## 开源的远眺
```

2022-03-08 08:17 UTC, tisonkun commented on source/_posts/opensource-code-spillover.md
> +对于个体贡献者而言，除了基于个人兴趣爱好或个体利益驱动参与开源贡献之外，则完全可以站在更高的立意上去看待自己对开源社区的代码贡献 —— 这是在推动人类社会的经济增长的有价值工作，将自己的代码开源置于全社会的公共知识体系之内，可能会因为自己的代码开源丧失局部的或者阶段性的经济利益，但却绝不会丧失自己作为人力资本本身的竞争力和垄断性。
```suggestion
对于个体贡献者而言，除了基于个人兴趣爱好或个体利益驱动参与开源贡献之外，则完全可以站在更高的立意上去看待自己对开源社区的代码贡献——这是在推动人类社会的经济增长的有价值工作，将自己的代码开源置于全社会的公共知识体系之内，可能会因为自己的代码开源丧失局部的或者阶段性的经济利益，但却绝不会丧失自己作为人力资本本身的竞争力和垄断性。
```

2022-03-10 11:17 UTC, kailakx commented on source/_posts/opensource-code-spillover.md
> +V=∑_(i=1)^n▒Vi                (2)
Is it correct for formula 2 if I write like this:  V=\sum_{i=1}^n \V_i}, and shall I put "$" before and after the  for formula?  For formula one, can I write just like this :Y_i=F(K_i,V,X_i)? Thanks your advise.

2022-03-10 11:20 UTC, kailakx commented on source/_posts/opensource-code-spillover.md
> +V=∑_(i=1)^n▒Vi=∑_(i=1)^n▒V(K_I,V,Xi) +V
For this formula, is it right if i wite like this: V=\sum_(i=1)^n\V（K_i,V,X_i)+V   
Thanks your help.

2022-03-10 12:15 UTC, tisonkun commented
Thanks for your updates @kailakx! Merging...

For formula rendering issues, I'll add an issue to dig it out. Either we can make use of mathjax alike solution or we just paste rendered pictures.

2022-03-10 12:16 UTC, tisonkun approved these changes

2022-03-10 12:16 UTC, merged